# Site settings
title: CI and CD with GitHub
description: A demo blog
email: training@github.com
twitter_username: githubtraining
github_username:  githubteacher
baseurl:
url: https://githubteacher-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
